#!/usr/bin/env bash
# Build a set of scratch projects to try `devc init` on by hand.
#
#   bash test/lab.sh [dir]          # create the lab (default: <repo>/.tmp/devc-lab)
#   bash test/lab.sh [dir] --smoke  # create it, then run the non-interactive
#                                   # pass over every folder and print exit codes
#
# Each folder exercises one path of the wizard; the README written at the
# lab root says which and how to run it. The lab is regenerated from scratch
# on every run — it is scratch, never a place to keep work.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEVC="node $HERE/bin/devc.mjs"
LAB="${1:-$(cd "$HERE/../.." && pwd)/.tmp/devc-lab}"
SMOKE=0
[ "${2:-}" = "--smoke" ] && SMOKE=1

[ -f "$HERE/dist/src/cli.js" ] || { echo "build first: cd $HERE && npm install && npm run build" >&2; exit 1; }

rm -rf "$LAB"
mkdir -p "$LAB"

# Dev Containers mounts the git root, not the folder (LOG §4.2). A `git init`
# in each project makes it its own root, so "Reopen in Container" opens the
# lab project and not the monorepo it sits under.
mk() { mkdir -p "$LAB/$1"; git -C "$LAB/$1" init -q; }

# 01 — nothing to detect: defaults all the way (stack Other, id from the dir name).
mk 01-empty

# 02 — Node project with its own package.json: detection + the textual merge
#      into an existing manifest (4-space indent, devDependencies present).
mk 02-node-app
mkdir -p "$LAB/02-node-app/src"
cat > "$LAB/02-node-app/package.json" <<'EOF'
{
    "name": "node-app",
    "version": "1.0.0",
    "scripts": {
        "test": "node --test"
    },
    "devDependencies": {
        "typescript": "^5.6.0"
    }
}
EOF
printf 'export const answer = 42\n' > "$LAB/02-node-app/src/index.ts"
printf 'export {}\n' > "$LAB/02-node-app/src/util.ts"

# 03 — PHP: composer.json wins over the package.json also present; the next
#      steps must point at stacks/php.md.
mk 03-php-app
mkdir -p "$LAB/03-php-app/src"
printf '{ "name": "acme/app", "require": { "php": ">=8.2" } }\n' > "$LAB/03-php-app/composer.json"
printf '{\n  "name": "acme-assets",\n  "private": true\n}\n' > "$LAB/03-php-app/package.json"
printf '<?php\necho "hi";\n' > "$LAB/03-php-app/src/index.php"
printf '<?php\nclass A {}\n' > "$LAB/03-php-app/src/A.php"

# 04 — Rust: no stack doc exists; the next steps say "add your toolchain".
mk 04-rust-tool
mkdir -p "$LAB/04-rust-tool/src"
printf '[package]\nname = "tool"\nversion = "0.1.0"\nedition = "2021"\n' > "$LAB/04-rust-tool/Cargo.toml"
printf 'fn main() { println!("hi"); }\n' > "$LAB/04-rust-tool/src/main.rs"
printf 'pub fn f() {}\n' > "$LAB/04-rust-tool/src/lib.rs"

# 05 — Capacitor Android plugin: capacitor.config.ts + gradle beat package.json.
mk 05-capacitor-plugin
mkdir -p "$LAB/05-capacitor-plugin/android/src/main/java/com/acme"
printf '{\n  "name": "acme-plugin",\n  "private": true\n}\n' > "$LAB/05-capacitor-plugin/package.json"
printf "import type { CapacitorConfig } from '@capacitor/cli'\nconst config: CapacitorConfig = { appId: 'com.acme', appName: 'acme', webDir: 'dist' }\nexport default config\n" > "$LAB/05-capacitor-plugin/capacitor.config.ts"
printf 'plugins { id "com.android.library" }\n' > "$LAB/05-capacitor-plugin/android/build.gradle"
printf 'package com.acme;\nclass Plugin {}\n' > "$LAB/05-capacitor-plugin/android/src/main/java/com/acme/Plugin.java"

# 06 — already scaffolded by this CLI: a re-run must report and do nothing;
#      one file is deleted so the re-run has something to add back.
mk 06-already-scaffolded
$DEVC init --yes --no-install --project-id already-there "$LAB/06-already-scaffolded" > /dev/null
rm "$LAB/06-already-scaffolded/.devcontainer/skills/disabled.txt"
printf '\n# hand edit, must survive\nMY_OWN_KEY=1\n' >> "$LAB/06-already-scaffolded/.devcontainer/.env"

# 07 — a v2 tree from install.sh: refused, exit 1, nothing touched.
mk 07-v2-legacy
mkdir -p "$LAB/07-v2-legacy/.devcontainer"
printf '{ "name": "legacy" }\n' > "$LAB/07-v2-legacy/.devcontainer/devcontainer.json"
printf 'FROM node:20\n' > "$LAB/07-v2-legacy/.devcontainer/Dockerfile.base"
printf '# Auto-generated by install.sh v2.1.0\nVERSION="2.1.0"\nPROJECT_ID="legacy"\n' > "$LAB/07-v2-legacy/.devcontainer/.configured-setup"

# 08 — another tool's devcontainer: refused, exit 1.
mk 08-foreign-devcontainer
mkdir -p "$LAB/08-foreign-devcontainer/.devcontainer"
printf '{ "image": "mcr.microsoft.com/devcontainers/base:ubuntu" }\n' > "$LAB/08-foreign-devcontainer/.devcontainer/devcontainer.json"

# 09 — a directory name the slug rules have to clean up.
mk '09-Weird_Dir.Name'

cat > "$LAB/README.md" <<EOF
# devc init — lab

Scratch projects to try \`devc init\` on by hand. Regenerate any time with
\`bash test/lab.sh\` (everything here is thrown away).

Run the wizard from a real terminal :

\`\`\`sh
# a function, not a variable: zsh does not word-split \$DEVC
devc() { node "$HERE/bin/devc.mjs" "\$@"; }
devc init $LAB/03-php-app          # interactive
devc init --yes $LAB/01-empty      # every default, no questions
devc init --dry-run $LAB/04-rust-tool
\`\`\`

Or, closer to what a user does, from the packed tarball :

\`\`\`sh
cd $HERE && npm pack --pack-destination /tmp
cd $LAB/02-node-app && npx --yes --package /tmp/meitogi-devcontainer-cli-0.1.0.tgz -- devc init
\`\`\`

| Folder | What it exercises | Expect |
|---|---|---|
| \`01-empty\` | nothing to detect | stack Other, id \`01-empty\`, name \`01 Empty\`, next step "add your toolchain" is absent (nothing detected → Other) |
| \`02-node-app\` | Node detection ; existing 4-space \`package.json\` with \`devDependencies\` | one line inserted before \`typescript\`, rest of the file byte-identical ; \`npm install\` offered |
| \`03-php-app\` | \`composer.json\` beats the \`package.json\` next to it | \`Detected: PHP (composer.json, …)\`, next step names \`stacks/php.md\` |
| \`04-rust-tool\` | a stack with no doc | Rust detected, "add your toolchain to the final stage" |
| \`05-capacitor-plugin\` | \`capacitor.config.ts\` + gradle beat \`package.json\` | Capacitor Android, \`stacks/android-capacitor.md\` |
| \`06-already-scaffolded\` | state 2 : a tree this CLI made, one file deleted, \`.env\` hand-edited | per-file report, \`skills/disabled.txt\` offered back, \`.env\` untouched (check \`MY_OWN_KEY\`) |
| \`07-v2-legacy\` | state 3 : \`Dockerfile.base\` + \`.configured-setup\` | \`devc init: refusing — … v2 layout made by install.sh\`, exit 1 |
| \`08-foreign-devcontainer\` | state 3 : another tool's \`devcontainer.json\` | refused, "without a customizations.stitchu-devc block", exit 1 |
| \`09-Weird_Dir.Name\` | slug sanitising | default id \`09-weird-dir-name\` ; type \`Bad Slug\` to see the re-ask |

Credentials-volume discovery reads this host's Docker : every \`claude-creds-*\`
volume shows up ranked by the projects that mount it. Stop Docker to see the
"docker did not answer" branch.

To boot one for real (\`code <folder>\` → Reopen in Container) : \`03-php-app\`
after a full run is the D13 scenario of TEST-PLAN-5 S5. Each folder is its
own git repo so Dev Containers mounts it and not the monorepo.
EOF

echo "lab at $LAB"
ls "$LAB"

if [ "$SMOKE" = 1 ]; then
  echo
  echo "=== smoke: devc init --yes --no-install on every folder (exit codes) ==="
  for d in "$LAB"/*/; do
    name="$(basename "$d")"
    set +e
    out="$($DEVC init --yes --no-install "$d" 2>&1 < /dev/null)"
    code=$?
    set -e
    last="$(printf '%s\n' "$out" | grep -E 'refusing|Nothing to do|Reopen in Container|\+ \.devcontainer/skills' | head -1 | cut -c1-90)"
    printf '  %-26s exit=%s  %s\n' "$name" "$code" "$last"
  done
  echo
  echo "expected: 01-05 and 09 → 0 (scaffolded) · 06 → 0 (report + skills/disabled.txt added) · 07, 08 → 1 (refused)"
fi
