// The install.sh fingerprints and the layout table, held against the real
// thing: templates/v2/ when the monorepo is present, and the top-level entry
// lists of the three v2 trees measured on 2026-09-23 (the dogfood, symptems,
// ragnarokonline) baked below — N=3 is the first time this project could
// tell "a v2 tree" from "this v2 tree".

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { detectLegacy, inventoryLegacy, LEGACY_LAYOUT, readLegacyMarker, type LegacyCategory } from '../src/lib/legacy.js'
import { PACKAGE_ROOT } from '../src/lib/version.js'

const MONOREPO_V2 = join(PACKAGE_ROOT, '..', '..', 'templates', 'v2')

const MARKER = `# Auto-generated by install.sh v2.0.0 — do not edit.
VERSION="2.0.0"
PROJECT_ID="symptems"
PROJECT_DISPLAY_NAME="Symptems"
PROJECT_TYPE="node"
CLAUDE_CREDS_VOLUME="claude-creds-shared-boa"
INSTALLED_AT="2026-05-29T08:10:59Z"
`

function scratch(): { dir: string; cleanup: () => void } {
	const dir = mkdtempSync(join(tmpdir(), 'devc-legacy-'))
	return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) }
}

test('readLegacyMarker: the six install.sh keys, quotes stripped, major from VERSION', () => {
	const { dir, cleanup } = scratch()
	try {
		const file = join(dir, '.configured-setup')
		writeFileSync(file, MARKER, 'utf8')
		const marker = readLegacyMarker(file)
		assert.ok(marker)
		assert.equal(marker.version, '2.0.0')
		assert.equal(marker.major, '2')
		assert.deepEqual(marker.fields, {
			VERSION: '2.0.0',
			PROJECT_ID: 'symptems',
			PROJECT_DISPLAY_NAME: 'Symptems',
			PROJECT_TYPE: 'node',
			CLAUDE_CREDS_VOLUME: 'claude-creds-shared-boa',
			INSTALLED_AT: '2026-05-29T08:10:59Z',
		})
		// Unquoted values and a missing VERSION line.
		writeFileSync(file, 'PROJECT_ID=bare\n', 'utf8')
		assert.deepEqual(readLegacyMarker(file), { version: '', major: '?', fields: { PROJECT_ID: 'bare' } })
		assert.equal(readLegacyMarker(join(dir, 'absent')), null)
	} finally {
		cleanup()
	}
})

test('detectLegacy: Dockerfile.base names v2 first; the marker alone names its own major; neither is null', () => {
	const { dir, cleanup } = scratch()
	try {
		const dc = join(dir, '.devcontainer')
		mkdirSync(dc)
		assert.equal(detectLegacy(dir), null)
		writeFileSync(join(dc, '.configured-setup'), 'VERSION="1.3.0"\n', 'utf8')
		assert.match(detectLegacy(dir)?.found ?? '', /^a v1 layout made by install\.sh \(\.configured-setup is present\)$/)
		writeFileSync(join(dc, 'Dockerfile.base'), 'FROM node\n', 'utf8')
		const both = detectLegacy(dir)
		assert.equal(both?.found, 'a v2 layout made by install.sh (Dockerfile.base is present)')
		assert.equal(both?.marker?.major, '1', 'the marker is still read when Dockerfile.base wins')
	} finally {
		cleanup()
	}
})

test(
	'LEGACY_LAYOUT names every top-level entry of templates/v2/',
	{ skip: !existsSync(MONOREPO_V2) && 'monorepo template not present' },
	() => {
		const missing = readdirSync(MONOREPO_V2).filter((name) => LEGACY_LAYOUT[name] === undefined)
		assert.deepEqual(missing, [])
	},
)

/** `ls -A .devcontainer` of each tree on 2026-09-23, and what is that tree's own. */
const REAL_TREES: Record<string, { entries: string[]; yours: string[] }> = {
	dogfood: {
		entries: `.DS_Store .configured-auth .configured-claude-mode .configured-setup .dockerignore .env .env.bak-4.3 .env.example .gitignore .gitignore-root .state-backup .wtfcmd.yaml .zsh-custom Dockerfile Dockerfile.AndroidMin Dockerfile.AndroidStd Dockerfile.CapacitorAndroidMin Dockerfile.CapacitorAndroidStd Dockerfile.base HOW-TO-CAPACITOR-PLUGIN.md LESSONS.local.md LESSONS.md README.md RESEARCH.md RUNBOOK.md SECURITY-AUDIT-2026-05.md SECURITY.md _archive cache claude claude-bridge devcontainer.json diag-ollama-local.sh docker-compose.yml firewall firewall-mode.sh host-helpers init-firewall.sh initialize initialize.sh install-extensions.sh knowledge logs notify on-create.sh pending post-create.sh post-start.sh reload-local.sh research-bundles scripts shareglaude.env shareglaude.env.example shell-init.sh skills test-firewall.sh tests vscode-macos vscode-settings.jsonc zshrc-base zshrc.local.example`.split(' '),
		yours: `.env.bak-4.3 .state-backup .wtfcmd.yaml .zsh-custom SECURITY-AUDIT-2026-05.md _archive shareglaude.env shareglaude.env.example vscode-macos`.split(' '),
	},
	symptems: {
		entries: `.DS_Store .configured-auth .configured-claude-mode .configured-setup .dockerignore .env .env.example .gitignore .gitignore-root Dockerfile Dockerfile.base LESSONS.md README.md RESEARCH.md RUNBOOK.md SECURITY.md claude claude-bridge devcontainer.json diag-ollama-local.sh docker-compose.yml firewall firewall-mode.sh host-helpers init-firewall.sh initialize initialize.sh install-extensions.sh knowledge logs notify on-create.sh orchestration pending post-create.sh post-start.sh pr-drafts shell-init.sh skills test-firewall.sh tests tmp vscode-settings.json zshrc-base zshrc.local.example`.split(' '),
		yours: `orchestration tmp vscode-settings.json`.split(' '),
	},
	ragnarokonline: {
		entries: `.DS_Store .configured-auth .configured-claude-mode .configured-setup .dockerignore .env .env.example .gitignore .gitignore-root .local Dockerfile Dockerfile.base Dockerfile.rizin-toolchain LESSONS.local.md LESSONS.md README.md RESEARCH.md RUNBOOK.md SECURITY.md bin claude claude-bridge devcontainer.json diag-ollama-local.sh docker-compose.yml firewall firewall-mode.sh host-helpers init-firewall.sh initialize initialize.sh install-extensions.sh knowledge logs notify on-create.sh pending post-create.sh post-start.sh pr-drafts shell-init.sh skills test-firewall.sh tests updates vscode-settings.json vscode-settings.jsonc zshrc-base zshrc.local zshrc.local.example`.split(' '),
		yours: `.local Dockerfile.rizin-toolchain bin updates vscode-settings.json`.split(' '),
	},
}

test('the three real v2 trees: every entry the template made is classified, and only their own land in "yours"', () => {
	for (const name in REAL_TREES) {
		const tree = REAL_TREES[name] as { entries: string[]; yours: string[] }
		const yours = tree.entries.filter((entry) => (LEGACY_LAYOUT[entry]?.category ?? 'yours') === 'yours').sort()
		assert.deepEqual(yours, [...tree.yours].sort(), name)
	}
})

test('inventoryLegacy reads the lifecycle lines, the FROM, the loader and .env — and marks directories', () => {
	const { dir, cleanup } = scratch()
	try {
		const dc = join(dir, '.devcontainer')
		mkdirSync(join(dc, 'skills'), { recursive: true })
		mkdirSync(join(dc, 'orchestration'))
		writeFileSync(join(dc, 'Dockerfile.base'), 'FROM node\n', 'utf8')
		writeFileSync(join(dc, 'Dockerfile'), '# slim layer\nARG X=1\nFROM claude-devcontainer-base:${CLAUDE_CODE_VERSION}-${DC_PROJECT}\nRUN true\n', 'utf8')
		writeFileSync(
			join(dc, 'devcontainer.json'),
			'{\n  // a comment\n  "initializeCommand": "bash .devcontainer/initialize.sh",\n  "onCreateCommand": "bash .devcontainer/on-create.sh",\n  "postStartCommand": "bash .devcontainer/post-start.sh",\n}\n',
			'utf8',
		)
		writeFileSync(join(dc, 'skills', 'sync-skills.sh'), '#!/bin/bash\n', 'utf8')
		writeFileSync(join(dc, '.env'), 'CLAUDE_CREDS_VOLUME=claude-creds-shared-boa\n', 'utf8')

		const tree = inventoryLegacy(dir)
		assert.equal(tree.initializeCommand, 'bash .devcontainer/initialize.sh')
		assert.deepEqual(tree.lifecycle, {
			onCreateCommand: 'bash .devcontainer/on-create.sh',
			postCreateCommand: null,
			postStartCommand: 'bash .devcontainer/post-start.sh',
		})
		assert.equal(tree.stitchuBlock, false)
		assert.equal(tree.dockerfileFrom, 'FROM claude-devcontainer-base:${CLAUDE_CODE_VERSION}-${DC_PROJECT}')
		assert.equal(tree.loader, true)
		assert.deepEqual(tree.env, { CLAUDE_CREDS_VOLUME: 'claude-creds-shared-boa' })
		const byName = Object.fromEntries(tree.entries.map((entry) => [entry.name, entry.category])) as Record<string, LegacyCategory>
		assert.equal(byName['skills/'], 'config')
		assert.equal(byName['orchestration/'], 'yours')
		assert.equal(byName['Dockerfile.base'], 'image')
		assert.equal(byName['.env'], 'config')
	} finally {
		cleanup()
	}
})

test('the claude/ note says the image ships no patcher (4.1i), not the reverse', () => {
	// The three real trees carry v2 copies of the shared patchers under
	// claude/vscode-ext-patchs/; ext-patches-sync merges local patchers over
	// the pinned set, so the note has to send them away, not call them shipped.
	const note = LEGACY_LAYOUT['claude']?.note ?? ''
	assert.match(note, /the image ships no patcher/)
	assert.doesNotMatch(note, /ship in the image/)
})
