// `devc migrate` reads a tree made by install.sh and prints; it never writes.
// The last property is the one a migration tool most needs proven, so it is
// asserted on the bytes, not on the code: the whole fixture is snapshotted
// before and after.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Writable } from 'node:stream'
import { migrate } from '../src/commands/migrate.js'
import { applyPlan, buildPlan } from '../src/lib/scaffold.js'
import { CLI_NAME, majorRange } from '../src/lib/version.js'

function scratch(): { dir: string; cleanup: () => void } {
	const dir = mkdtempSync(join(tmpdir(), 'devc-migrate-'))
	return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) }
}

function sink(): Writable & { text: () => string } {
	const chunks: string[] = []
	const stream = new Writable({
		write(chunk, _encoding, callback) {
			chunks.push(String(chunk))
			callback()
		},
	}) as Writable & { text: () => string }
	stream.text = () => chunks.join('')
	return stream
}

function run(dir: string, targetDir?: string): { code: number; out: string; err: string } {
	const out = sink()
	const err = sink()
	const code = migrate({ cwd: dir, targetDir, out, err })
	return { code, out: out.text(), err: err.text() }
}

/** Every path under `dir` with its bytes and mode — the "wrote nothing" oracle. */
function snapshot(dir: string, prefix = ''): Record<string, string> {
	const result: Record<string, string> = {}
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const abs = join(dir, entry.name)
		const rel = `${prefix}${entry.name}`
		if (entry.isDirectory()) {
			result[`${rel}/`] = String(statSync(abs).mode)
			Object.assign(result, snapshot(abs, `${rel}/`))
		} else {
			result[rel] = `${statSync(abs).mode}:${readFileSync(abs, 'utf8')}`
		}
	}
	return result
}

/** A v2 tree the size of the fingerprints: the two markers, the three hand-edited files, one of each category. */
function v2Fixture(dir: string, options: { dcProject?: boolean } = {}): void {
	const dc = join(dir, '.devcontainer')
	for (const sub of ['skills', 'notify', 'orchestration', 'logs', 'initialize']) mkdirSync(join(dc, sub), { recursive: true })
	writeFileSync(join(dc, 'Dockerfile.base'), 'FROM node:24\n', 'utf8')
	writeFileSync(
		join(dc, '.configured-setup'),
		'# Auto-generated by install.sh v2.0.0 — do not edit.\nVERSION="2.0.0"\nPROJECT_ID="symptems"\nPROJECT_DISPLAY_NAME="Symptems"\nPROJECT_TYPE="node"\nCLAUDE_CREDS_VOLUME="claude-creds-shared-boa"\nINSTALLED_AT="2026-05-29T08:10:59Z"\n',
		'utf8',
	)
	writeFileSync(join(dc, 'Dockerfile'), 'ARG CLAUDE_CODE_VERSION=2.1.145\nFROM claude-devcontainer-base:${CLAUDE_CODE_VERSION}-${DC_PROJECT}\n', 'utf8')
	writeFileSync(join(dc, 'docker-compose.yml'), 'services: {}\n', 'utf8')
	writeFileSync(
		join(dc, 'devcontainer.json'),
		'{\n  "name": "Symptems — Claude Code Sandbox",\n  "initializeCommand": "bash .devcontainer/initialize.sh",\n  "onCreateCommand": "bash .devcontainer/on-create.sh",\n  "postCreateCommand": "bash .devcontainer/post-create.sh",\n  "postStartCommand": "bash .devcontainer/post-start.sh",\n}\n',
		'utf8',
	)
	writeFileSync(join(dc, 'initialize.sh'), '#!/bin/bash\n', 'utf8')
	writeFileSync(join(dc, 'skills', 'sync-skills.sh'), '#!/bin/bash\n', 'utf8')
	writeFileSync(join(dc, '.env'), `${options.dcProject ? 'DC_PROJECT=symptems\n' : ''}CLAUDE_CREDS_VOLUME=claude-creds-shared-boa\n`, 'utf8')
}

test('a v2 tree gets the report, exit 0, and not one byte changes', () => {
	const { dir, cleanup } = scratch()
	try {
		v2Fixture(dir)
		const before = snapshot(dir)
		const { code, out, err } = run(dir)
		assert.equal(code, 0, err)
		assert.equal(err, '')
		assert.deepEqual(snapshot(dir), before)

		// What was found — the tree's own values, not placeholders.
		assert.match(out, /This is a v2 layout made by install\.sh \(Dockerfile\.base is present\)/)
		assert.match(out, /marker: +\.configured-setup v2\.0\.0, installed 2026-05-29T08:10:59Z/)
		assert.match(out, /project: +symptems — "Symptems" \(node\)/)
		assert.match(out, /DC_PROJECT: +symptems +MISSING in \.env — step 5/)
		assert.match(out, /creds volume: +claude-creds-shared-boa +\.env: set/)
		assert.match(out, /Dockerfile: +FROM claude-devcontainer-base:.*local lineage, built by initialize\.sh/)
		assert.match(out, /initializeCommand: +bash \.devcontainer\/initialize\.sh/)
		assert.match(out, /lifecycle: +bash \.devcontainer\/on-create\.sh · bash \.devcontainer\/post-create\.sh · bash \.devcontainer\/post-start\.sh/)
		assert.match(out, /stitchu-devc block: +absent/)
		assert.match(out, /skills loader: +skills\/sync-skills\.sh present/)

		// The entries, by what becomes of them.
		assert.match(out, /\.devcontainer\/ entries \(12\)/)
		assert.match(out, /^ {4}config \(6\)/m)
		assert.match(out, /^ {4}image \(1\)[^\n]*\n {6}Dockerfile\.base$/m)
		assert.match(out, /^ {4}pending \(1\)[^\n]*\n {6}notify\/$/m)
		assert.match(out, /^ {4}retired \(1\)[^\n]*\n {6}initialize\/$/m)
		assert.match(out, /^ {4}runtime \(2\)[^\n]*\n {6}\.configured-setup  logs\/$/m)
		assert.match(out, /^ {4}yours \(1\)[^\n]*\n {6}orchestration\/$/m)

		// The checklist carries the values and the exact npx line the scaffold uses.
		assert.match(out, new RegExp(`\\d\\. initialize\\.sh .*\\n.*execs \`npx --yes ${CLI_NAME.replace('/', '\\/')}@${majorRange().replace('.', '\\.')} initialize\``))
		assert.match(out, /\d\. \.env +DC_PROJECT=symptems and CLAUDE_CREDS_VOLUME=claude-creds-shared-boa\n.*at least one is missing here/)
		assert.match(out, /\d\. remove +Dockerfile\.base, the Dockerfile\.<stack> variants, \.configured-setup/)
		assert.match(out, /"customizations": \{ "stitchu-devc": \{\} \}/)
		assert.match(out, /devc-hook post-start --dry-run/)
		assert.match(out, /\n  Nothing was written\.\n$/)
	} finally {
		cleanup()
	}
})

test('a marker-only tree (no Dockerfile.base) is still reported, from the marker', () => {
	const { dir, cleanup } = scratch()
	try {
		v2Fixture(dir, { dcProject: true })
		rmSync(join(dir, '.devcontainer', 'Dockerfile.base'))
		const { code, out } = run(dir)
		assert.equal(code, 0)
		assert.match(out, /This is a v2 layout made by install\.sh \(\.configured-setup is present\)/)
		assert.match(out, /DC_PROJECT: +symptems +\.env: set/)
		assert.match(out, /both already set here/)
	} finally {
		cleanup()
	}
})

test('nothing to migrate: absent, scaffolded by this CLI, made by another tool — exit 1, and still nothing written', () => {
	const { dir, cleanup } = scratch()
	try {
		const absent = run(dir)
		assert.equal(absent.code, 1)
		assert.match(absent.err, /^devc migrate: nothing to migrate — no \.devcontainer\/ here — devc init scaffolds one\n$/)
		assert.equal(absent.out, '')

		applyPlan({
			projectDir: dir,
			plan: buildPlan({ projectId: 'demo-app', displayName: 'Demo App', stack: 'node', credsVolume: null, claudeCodeVersion: '2.1.272' }),
			dryRun: false,
		})
		const before = snapshot(dir)
		const same = run(dir)
		assert.equal(same.code, 1)
		assert.match(same.err, /scaffolded by this CLI — devc init reports it/)
		assert.deepEqual(snapshot(dir), before)

		writeFileSync(join(dir, '.devcontainer', 'devcontainer.json'), '{ "image": "mcr.microsoft.com/devcontainers/base" }\n', 'utf8')
		const foreign = run(dir)
		assert.equal(foreign.code, 1)
		assert.match(foreign.err, /without a customizations\.stitchu-devc block — not a tree install\.sh made/)
	} finally {
		cleanup()
	}
})

test('a target that does not exist is a usage error, and [dir] is honoured', () => {
	const { dir, cleanup } = scratch()
	try {
		assert.equal(run(dir, 'nope').code, 2)
		mkdirSync(join(dir, 'sub'))
		v2Fixture(join(dir, 'sub'))
		assert.equal(run(dir, 'sub').code, 0)
		assert.equal(run(dir).code, 1)
	} finally {
		cleanup()
	}
})
